src/Entity/Adverts.php
<?php

namespace App\Entity;

use App\Repository\AdvertsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdvertsRepository::class)
 */
class Adverts
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $picture;

      /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="adverts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Region", inversedBy="adverts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $region;

     /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="adverts")
     * @ORM\JoinColumn(nullable=false)
     */

    private $user;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Get the value of category
     */ 
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Set the value of category
     *
     * @return  self
     */ 
    public function setCategory($category)
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get the value of region
     */ 
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Set the value of region
     *
     * @return  self
     */ 
    public function setRegion($region)
    {
        $this->region = $region;

        return $this;
    }

    /**
     * Get the value of user
     */ 
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set the value of user
     *
     * @return  self
     */ 
    public function setUser($user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get the value of picture
     */ 
    public function getPicture()
    {
        return $this->picture;
    }

    /**
     * Set the value of picture
     *
     * @return  self
     */ 
    public function setPicture($picture)
    {
        $this->picture = $picture;

        return $this;
    }
}

src/Form/AdvertType.php
<?php

namespace App\Form;

use App\Entity\Adverts;
use Symfony\Component\Console\Input\Input;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use function PHPSTORM_META\type;

class AdvertType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('price')
            ->add('email')
            ->add('phone')
            ->add('category')
            ->add('region')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Adverts::class,
        ]);
    }
}

src/Controller/AdvertsController.php
<?php

namespace App\Controller;

use App\Entity\Adverts;
use App\Form\AdvertType;
use App\Repository\CategoryRepository;
use App\Repository\RegionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class AdvertsController extends AbstractController
{
    /**
     * @Route("/", name="advert_list")
     */
    public function index(Request $request, PaginatorInterface $paginator): Response
    {

        $donnees = $this->getDoctrine()->getRepository(Adverts::class)->findBy([],['created_at' => 'desc']);

        $adverts = $paginator->paginate(
            $donnees, // Requête contenant les données à paginer (ici nos articles)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            9 // Nombre de résultats par page
        );

        return $this->render('adverts/list.html.twig', ['adverts' => $adverts]);
    }

    /**
     * @Route("/add-advert", name="advert_add")
     * @param Request $request
     */
    public function add(Request $request, EntityManagerInterface $entityManager, ValidatorInterface $validator)
    {
        $advert = new Adverts();
        $advert->setUser($this->getUser());
        $advert->setPicture($request->request->get('picture'));

        $form = $this->createForm(AdvertType::class, $advert);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($advert);
            $entityManager->flush();

            return $this->redirectToRoute('gestion');
        }
        $errors = $validator->validate($advert);
        if (count($errors) > 0) {
            return new Response((string) $errors, 400);
        }

        return $this->render('adverts/add.html.twig', [

            'form' => $form->createView(),
        ]);
        
    }   

    /**
     * @Route("/advert/update/{id}", name="advert_show" )
     */
    public function update(int $id,RegionRepository $regionRepository, CategoryRepository $categoryRepository, Request $request,
     ValidatorInterface $validator): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $advert = $entityManager->getRepository(Adverts::class)->find($id);

        if (!$advert) {
            throw $this->createNotFoundException(
                'No product found for id '.$id
            );
        }

        $advert->setUser($this->getUser());
       // $advert->setPicture($request->request->get('picture'));

        $form = $this->createForm(AdvertType::class, $advert);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($advert);
            $entityManager->flush();

            return $this->redirectToRoute('gestion');
        }
        $errors = $validator->validate($advert);
        if (count($errors) > 0) {
            return new Response((string) $errors, 400);
        }
       
        return $this->render('adverts/update.html.twig', [

            'form' => $form->createView(),
        ]);
        $this->addFlash('success', 'Mise à jour efféctué.');
    }
    
    /**
     * @Route("/delete/{id}", name="advert_delete")
     * @return Response
     */

    public function delete(Adverts $adverts) {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($adverts);
        $entityManager->flush();
        $this->addFlash('success', 'Annonce supprimé.');
        //return new Response('annonce suprimée');
        return $this->redirectToRoute('gestion');
    }


}

templates/adverts/add.html.twig
{% extends "base.html.twig" %}
{% block header %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <img src="http://localhost:8888/symfony/boncoin/assets/img/affaire.png" style="width: 110px;">
   
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href=" {{ path('advert_list')}}">Retour vers page d'accueil</a>
        </li>
        <li class="nav-item">

          <a class="nav-link" href="{{path('gestion')}}">Gérer mes annonces</a>

        </li>
        <li class="nav-item">

          <a class="nav-link" href=" {{ path('user_logout')}}">Se déconnecter</a>

        </li>

      </ul>
    </div>
  </nav>

{% endblock %}

{% block body %}
<div class="container">
  <div class="form">
    <div class="row d-flex justify-content-center">
      <div class="col-md-4">
    {{ form_start(form) }}
    {{ form_widget(form) }}
    Photo :
    <input type="file" name="picture"><br>
    <button type="submit">Ajouter</button>
    {{ form_end(form) }}
 </div>
 </div>
 </div>
 </div>

  </div>
{% endblock %}

templates/adverts/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AdvertsController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Applications/MAMP/htdocs/symfony/boncoin/src/Controller/AdvertsController.php'|file_link(0) }}">src/Controller/AdvertsController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Applications/MAMP/htdocs/symfony/boncoin/templates/adverts/index.html.twig'|file_link(0) }}">templates/adverts/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/adverts/list.html.twig
{% extends "base.html.twig" %}
{% block header %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <img src="http://localhost:8888/symfony/boncoin/assets/img/affaire.png" style="width: 110px;">

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href=" {{ path('app_login')}}">Se connecter
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=" {{ path('user_add')}}">S'inscrire</a>
        </li>

      </ul>
    </div>
  </nav>

{% endblock %}

{% block body %}


  <div class="container-fluid py-5">
    <div class="p-5 mb-4 bg-light rounded-3">
      <h1 class="display-5 fw-bold d-flex justify-content-center">Toutes nos annonces</h1>
      <center>
        <p class="col-md-8 fs-4 ">Peu importe ce que vous cherchez, ici vous trouverez !</p>
      </center>
      <a class="btn  btn-lg  d-flex justify-content-center" href=" {{ path('search_adverts')}}" role="button">Recherche Avancée</a>
    </div>
  </div>

  <form>
    <div class="container">
      <div class="card-deck">

        <div class="row">
          {% for advert in adverts %}
            <div class="col-lg-4 col-md-6 col-sm-12">

              <div class="card">

                <img class="card-img-top" style="height: 280px;" src="http://localhost:8888/symfony/boncoin/assets/img/{{advert.picture}}" alt="card ">

                <div class="card-body">
                  <p class="card-text">Catégorie de l'annonce :
                    {{ advert.category.name }}
                  </p>
                  <p class="card-text">Titre de l'annonce :
                    {{ advert.title }}
                  </p>

                  <small class="text-muted">Ajouté le :
                    {{ advert.createdAt|date('Y-m-d') }}
                  </small><br>
                  <small class="text-muted">Description :
                    {{ advert.description }}
                  </small><br>
                  <small class="text-muted">Prix :
                    {{ advert.price }}
                    Euros</small><br>
                  <small class="text-muted">Région :
                    {{ advert.region.name}}
                  </small>
                  <h2>Me contacter</h2>
                  <small class="text-muted">Téléphone:
                    {{ advert.phone }}</small><br>
                  <small class="text-muted">Email :
                    <a href="mailto:{{ advert.Email }}">{{ advert.Email }}</a>
                  </small>
                </div>
              </div>
            </div>

          {% endfor %}
          {{ knp_pagination_render(adverts) }}
        </div>

      </div>
    </div>
  </form>
  <section id="produits">
    <div class="container">
      <h2>Nos derniers produits</h2>
      <!-- Use Bootstrap Carousel without indicators -->
      <div class="carousel slide" data-ride="carousel" id="presentation-carousel" data-interval="3000">
        <div class="carousel-inner">
          <div class="carousel-item active">

            <figure>
              <img src="{{ asset('http://localhost:8888/symfony/boncoin/assets/img/pexels-photo-276517.jpeg')}}" style="height: 280px;" alt="" class="img-fluid">
              <figcaption>Vélo Rockrider</figcaption>
            </figure>
          </div>
          <div class="carousel-item">
            <figure>
              <img src="{{ asset('http://localhost:8888/symfony/boncoin/assets/img/pexels-photo-3757055.jpeg')}}" style="height: 280px;" alt="" class="img-fluid">
              <figcaption>Canapé chateau d'ax</figcaption>
            </figure>

          </div>
          <div class="carousel-item">
            <figure>
              <img src="{{ asset('http://localhost:8888/symfony/boncoin/assets/img/pexels-photo-1323201.jpeg')}}" style="height: 280px;" alt="" class="img-fluid">

              <figcaption>Casque converse</figcaption>
            </figure>

          </div>

          <div class="carousel-item">
            <figure>
              <img src="{{('http://localhost:8888/symfony/boncoin/assets/img/macbook-apple-imac-computer-39284.jpeg')}}" style="height: 280px;" alt="" class="img-fluid">
              <figcaption>MacBook Pro i7</figcaption>
            </figure>

          </div>

        </div>

      </div>

    </div>

  </section>
{% endblock %}

templates/adverts/search.html.twig
{% extends "base.html.twig" %}
{% block header %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <img src="http://localhost:8888/symfony/boncoin/assets/img/affaire.png" style="width: 110px;">
   
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href=" {{ path('advert_list')}}">Retour vers page d'accueil</a>
        </li>

      </ul>
    </div>
  </nav>

{% endblock %}
{% block title %}Recherche {% endblock %}
{% block body %}

  <div class="container">
   
  <div class="form">
    <div class="row d-flex justify-content-center">
      <div class="col-md-4">
          <div id="sel">
        {{ form_start(search_form) }}
 
        {{ form_widget(search_form) }}
             </div>
        <button type="submit">Recherche</button>
        {{ form_end(search_form) }}
     
      </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="card-deck">

      <div class="row">
        {% for advert in adverts %}
          <div class="col-md-4 col-sm-12">

            <div class="card" style="width=21rem;">

              <img class="card-img-top" style="height: 280px;" src="http://localhost:8888/symfony/boncoin/assets/img/{{advert.picture}}" alt="card ">
              <div class="card-body">
                <p class="card-text">Catégorie de l'annonce :
                  {{ advert.category.name }}
                </p>
                <p class="card-text">Titre de l'annonce :
                  {{ advert.title }}
                </p>
                    <p class="card-text">Description :
                    {{ advert.description }}
                  </p>
                <small class="text-muted">Ajouté le :
                  {{ advert.createdAt|date('Y-m-d') }}
                </small><br>

                <small class="text-muted">Prix :
                  {{ advert.price }}
                  Euros</small><br>
                <small class="text-muted">Région :
                  {{ advert.region.name}}
                </small>
                <h2>Me contacter</h2>
                <small class="text-muted">Téléphone:
                  {{ advert.phone }}</small><br>
                <small class="text-muted">Email :
                  {{ advert.Email }}
                </small>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>

    </div>
  </div>

{% endblock %}

templates/adverts/show.html.twig
{% extends "base.html.twig" %}
{% block header %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <img src="http://localhost:8888/symfony/boncoin/assets/img/affaire.png" style="width: 110px;">

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">

          {% if is_granted('ROLE_ADMIN') %}

          <li >
            <a class="nav-link" href=" {{ path('advert_list')}}">Retour vers page d'accueil</span></a>
        </li>
        <li class="nav-item">

          <a class="nav-link" href=" {{ path('user_logout')}}">Se déconnecter</a>

        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href=" {{ path('advert_list')}}">Retour vers page d'accueil</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=" {{ path('advert_add')}}">Ajouter une annonce</span></a>
    </li>
    <li class="nav-item">

      <a class="nav-link" href=" {{ path('user_logout')}}">Se déconnecter</a>

    </li>

  {% endif %}
</ul>
</div>
</nav>
{% endblock %}
{% block body %}
{% if is_granted('ROLE_ADMIN') %}
<div class="container">
<div class="form">
  <div class="row d-flex justify-content-center">
    <div class="col-md-12">
      <a class="btn  btn-lg  d-flex justify-content-center" href=" {{ path('admin_users')}}" role="button">Gerer les users</span></a>
  </div>
  <div class="col-md-12">
    <a class="btn  btn-lg  d-flex justify-content-center" href=" {{ path('admin')}}" role="button">Gerer les annonces</a>
  </div>
</div>
</div>
</div>
{% endif %}
<form>
<div class="container">
<div class="card-deck">

<div class="row">
  {% for advert in adverts %}
    <div class="col-lg-4 col-md-6 col-sm-12">

      <div class="card">

        <img class="card-img-top" style="height: 280px;" src="http://localhost:8888/symfony/boncoin/assets/img/{{advert.picture}}" alt="card ">
        <div class="card-body">
          <p class="card-text">Catégorie de l'annonce :
            {{ advert.category.name }}
          </p>
          <p class="card-text">Titre de l'annonce :
            {{ advert.title }}
          </p>
          <small class="text-muted">Ajouté le :
            {{ advert.createdAt|date('Y-m-d') }}
          </small><br>

          <small class="text-muted">Prix :
            {{ advert.price }}
            Euros</small><br>
          <small class="text-muted">Région :
            {{ advert.region.name}}
          </small>
          <hr>
          <a href=" {{ path('advert_delete', {'id':advert.id})}}">Supprimer cette l'annonce 🙈</a><br>
          <a href=" {{ path('advert_show', {'id':advert.id})}}">Mise à jour de l'annonce 🙉</a>
        </div>
      </div>
    </div>

  {% endfor %}

</div>

</div>
</div>
</form>
{% endblock %}

templates/adverts/update.html.twig
{% extends "base.html.twig" %}
{% block header %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <img src="http://localhost:8888/symfony/boncoin/assets/img/affaire.png" style="width: 110px;">
 
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href=" {{ path('advert_list')}}">Retour vers page d'accueil</a>
        </li>
        <li class="nav-item">

          <a class="nav-link" href="{{path('gestion')}}">Gérer mes annonces</a>

        </li>
        <li class="nav-item">

          <a class="nav-link" href=" {{ path('user_logout')}}">Se déconnecter</a>

        </li>

      </ul>
    </div>
  </nav>

{% endblock %}

{% block body %}
<div class="container">
  <div class="form">
    <div class="row d-flex justify-content-center">
      <div class="col-md-4">
    {{ form_start(form) }}
    {{ form_widget(form) }}
    Photo :

    <button type="submit">Mettre à jour</button>
    {{ form_end(form) }}
 </div>
 </div>
 </div>
 </div>

  </div>
{% endblock %}